display group and version as annotation in the generated POJOs
goldmansachs/crdtools pull request #38
Opened 2022-08-05 14:37 UTC by alfredomusumeci

This PR now adds group and version as annotation in the generated POJOs.
An example of POJO:

```Java
/**
 * CronTab
 */
@Validated
@javax.annotation.Generated(group = "stable.example.com", version = "v1")
@JsonInclude(JsonInclude.Include.NON_NULL)

public class CronTab extends BaseObject  {
...
}
```

UnitTesting is also added to see if the annotation is actually present in the generated output.

2022-08-09 13:16 UTC, alfredomusumeci commented
Ignore this for now, it is being updated

2022-08-09 14:44 UTC, alfredomusumeci commented
Updated, ready for review

2022-08-09 14:56 UTC, nresare requested changes

2022-08-09 14:56 UTC, nresare commented on WORKSPACE
> +    commit = "fba01c14d03ee24a57ddeb67b922154fa1d31401",
this should be in a separate commit

2022-08-09 14:56 UTC, nresare commented on src/main/resources/swaggerTemplateOverloads/generatedAnnotation.mustache
> +{{#apiInformation}}
this is always true, right? I would remove the variable and reduce the complexity a tiny bit

2022-08-09 14:56 UTC, nresare commented on src/test/java/com/gs/crdtools/GeneratorTest.java
> +    static void setUp() throws IOException {
I realise that this is subjective, but I dislike setting up the input data in a `@BeforeAll` method. I would much rather have the extra bit of redundancy of having the data that the test operates on be explicitly created at the top of each test method. The reason for this is that it makes sense to optimise for few indirections for the person coming later and working with the test cases

2022-08-10 10:03 UTC, nresare approved these changes

2022-08-10 10:05 UTC, merged